apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../base/resources/gateway

patches:
  # Patch Gateway listener hostnames for etcd.me domain
  - target:
      kind: Gateway
      name: main-gateway
    patch: |
      - op: replace
        path: /spec/listeners/0/hostname
        value: "*.etcd.me"
      - op: replace
        path: /spec/listeners/1/hostname
        value: "*.etcd.me"

  # Patch Certificate dnsNames for etcd.me domain
  - target:
      kind: Certificate
      name: wildcard-tls
    patch: |
      - op: replace
        path: /spec/dnsNames
        value:
          - "*.etcd.me"
          - etcd.me

  # Patch HTTP redirect hostname
  - target:
      kind: HTTPRoute
      name: http-to-https-redirect
    patch: |
      - op: replace
        path: /spec/hostnames/0
        value: "*.etcd.me"
